# Generated by Django 3.2.3 on 2021-08-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0002_auto_20210814_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arte.categoria'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arte.tags'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='tematica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arte.tematica'),
        ),
    ]
