# Generated by Django 3.2.3 on 2021-08-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0009_alter_arte_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='arte',
            name='resolucao',
            field=models.CharField(default=0, max_length=15, verbose_name='Resolução'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arte',
            name='descricao',
            field=models.TextField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.RemoveField(
            model_name='arte',
            name='tags',
        ),
        migrations.AddField(
            model_name='arte',
            name='tags',
            field=models.ManyToManyField(to='arte.Tags'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='tematica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arte.tematica', verbose_name='Temática'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='nome',
            field=models.CharField(max_length=15),
        ),
    ]
