# Generated by Django 3.2.3 on 2021-08-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0011_alter_arte_resolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='nome',
            field=models.CharField(max_length=75),
        ),
    ]
