# Generated by Django 3.2.3 on 2021-08-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0015_auto_20210826_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='formato',
            field=models.CharField(choices=[('1', 'BPM'), ('2', 'TIFF'), ('3', 'JPEG'), ('4', 'GIF'), ('5', 'PNG'), ('6', 'EPS'), ('7', 'SVG'), ('8', 'PNG')], default='Sem detalhes', max_length=1),
        ),
    ]
