# Generated by Django 3.2.3 on 2021-08-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0017_alter_arte_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='formato',
            field=models.CharField(choices=[('BPM', 'BPM'), ('TIFF', 'TIFF'), ('JPEG', 'JPEG'), ('GIF', 'GIF'), ('PNG', 'PNG'), ('EPS', 'EPS'), ('SVG', 'SVG'), ('PNG', 'PNG')], default='Sem detalhes', max_length=4),
        ),
    ]
