# Generated by Django 3.2.3 on 2021-09-02 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0018_alter_arte_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arte.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arte',
            name='formato',
            field=models.CharField(choices=[('BPM', 'BPM'), ('TIFF', 'TIFF'), ('JPEG', 'JPEG'), ('JPG', 'JPG'), ('GIF', 'GIF'), ('PNG', 'PNG'), ('EPS', 'EPS'), ('SVG', 'SVG')], default='Sem detalhes', max_length=4),
        ),
        migrations.AlterField(
            model_name='arte',
            name='foto',
            field=models.ImageField(height_field='image_width', upload_to='media', width_field='image_height'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='tematica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arte.tematica', verbose_name='Temática'),
            preserve_default=False,
        ),
    ]
