# Generated by Django 3.2.3 on 2021-09-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0020_alter_arte_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arte',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=75)),
                ('comentario', models.CharField(max_length=150)),
                ('nota', models.IntegerField()),
                ('arte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arte.arte', verbose_name='Comentários')),
            ],
        ),
    ]
