# Generated by Django 3.2.3 on 2021-09-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0021_auto_20210914_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
