# Generated by Django 3.2.3 on 2021-09-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0025_alter_arte_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='arte',
            name='slug',
        ),
    ]
